version: "3"

volumes:
  portainer_data:
  couchbase_data:
  postgres_data:

services:

  portainer:
    image: portainer/portainer-ce
    container_name: op_portainer
    command: -H unix:///var/run/docker.sock
    restart: unless-stopped
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  couchbase:
    image: couchbase
    container_name: db_couchbase
    restart: unless-stopped
    ports:
      - 8091-8094:8091-8094
      - 11210:11210
    env_file:
      - env/couchbase.env
    volumes:
      - couchbase_data:/opt/couchbase/var

  postgres:
    image: postgres
    container_name: db_postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - env/postgres.env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  adminer:
    image: adminer
    container_name: db_postgres_client
    restart: unless-stopped
    ports:
      - 8080:8080